'use client'
import { useState, useEffect, useRef } from "react";
import Link from "next/link";

export default function Glossary({ className = "", classNameInput="", draggable = false }){
    const [term, setTerm] = useState("");
    const [height, setHeight] = useState("")

    const glosario = [
        {english: "Abortion", spanish: "Aborto, aborto voluntario", link: "https://medlineplus.gov/ency/article/002912.htm"},
        {english: "Aches and pains", spanish: "Dolores y molestias, Dolores y achaques", link: "https://medlineplus.gov/ency/patientinstructions/000580.htm"},
        {english: "Acid reflux", spanish: "Reflujo gástrico", link: "https://dictionary.cambridge.org/dictionary/english-spanish/reflux"},
        {english: "Acquired Immune Deficiency Syndrome (AIDS)", spanish: "Síndrome de Inmunodeficiencia Adquirida (SIDA)", link: "https://www.mayoclinic.org/diseases-conditions/hiv-aids/symptoms-causes/syc-20373524"},
        {english: "Acute pain", spanish: "Aborto, aborto voluntario", link: "https://medlineplus.gov/ency/article/002215.htm"},
        { english: 'Adenoids', spanish: 'Adenoides' , link: "https://medlineplus.gov/adenoids.html"},
        { english: 'Adenoidectomy', spanish: 'Adenoidectomía', link: "https://medlineplus.gov/ency/article/003011.htm"},
        { english: 'Admit', spanish: 'Ingresar, Internar' },
        { english: 'Advance (medical) directive', spanish: 'Directriz (médica) anticipada', link: "https://medlineplus.gov/ency/patientinstructions/000472.htm" },
        { english: 'Advice nurse', spanish: 'Enfermero de orientación médica, Enfermero asesor' },
        { english: 'Airways', spanish: 'Vías respiratorias' },
        { english: 'Allergen', spanish: 'Alérgeno', link:"https://medlineplus.gov/ency/article/002229.htm" },
        { english: 'Allergist', spanish: 'Alergólogo' },
        { english: 'Allergy', spanish: 'Alergia', link: "https://medlineplus.gov/allergy.html"},
        { english: 'Allergy skin test', spanish: 'Prueba cutánea de alergia, Prueba de alergia en la piel', link: "https://medlineplus.gov/ency/article/003519.htm" },
        { english: 'Alzheimer\'s disease', spanish: 'Enfermedad de Alzheimer', link: "https://medlineplus.gov/ency/article/000760.htm" },
        { english: 'Amniotic fluid', spanish: 'Líquido amniótico', link:"https://medlineplus.gov/ency/article/002220.htm" },
        { english: 'Amniotic Sac', spanish: 'Saco amniótico' },
        { english: 'Analgesic, Painkiller', spanish: 'Analgésico', link: "https://medlineplus.gov/painrelievers.html" },
        { english: 'Anesthesia', spanish: 'Anestesia', link: "https://medlineplus.gov/anesthesia.html" },
        { english: 'Angina pectoris', spanish: 'Angina de pecho', link: "https://www.mayoclinic.org/diseases-conditions/angina/symptoms-causes/syc-20369373" },
        { english: 'Ankle', spanish: 'Tobillo' },
        { english: 'Antibacterial', spanish: 'Antibacteriano' },
        { english: 'Antibiotic', spanish: 'Antibiótico' },
        { english: 'Anticoagulant, Blood thinner', spanish: 'Anticoagulante, Diluyente sanguíneo' },
        { english: 'Antidepressant', spanish: 'Antidepresivo', link:"https://medlineplus.gov/antidepressants.html" },
        { english: 'Antifungal', spanish: 'Antifúngico, Antimicótico, Antihongos' },
        { english: 'Antihistamine', spanish: 'Antihistamínico', link:"https://medlineplus.gov/ency/patientinstructions/000549.htm" },
        { english: 'Anti-inflammatory', spanish: 'Antiinflamatorio' },
        { english: 'Anxiety', spanish: 'Ansiedad', link:"https://medlineplus.gov/anxiety.html" },
        { english: 'Anxiety disorder', spanish: 'Trastorno de ansiedad', link: "https://medlineplus.gov/ency/article/000957.htm" },
        { english: 'Appendectomy', spanish: 'Apendicectomía', link:"https://medlineplus.gov/ency/article/002921.htm" },
        { english: 'Appendix', spanish: 'Apéndice' },
        { english: 'Armpit', spanish: 'Axila' },
        { english: 'Arrhythmia', spanish: 'Arritmia', link:"https://medlineplus.gov/arrhythmia.html" },
        { english: 'Artificial insemination', spanish: 'Inseminación artificial' },
        { english: 'Asthma', spanish: 'Asma', link:"https://medlineplus.gov/asthma.html" },
        { english: 'Athlete\'s foot', spanish: 'Pie de atleta', link:"https://medlineplus.gov/athletesfoot.html" },
        { english: 'Attending physician', spanish: 'Médico tratante, Médico adjunto' },
        { english: 'Attention Deficit Disorder (ADD)', spanish: 'Trastorno por Déficit de Atención (TDA)', link:"https://medlineplus.gov/attentiondeficithyperactivitydisorder.html" },
        { english: 'Attention Deficit Hyperactivity Disorder (ADHD)', spanish: 'Trastorno por Déficit de Atención e Hiperactividad (TDAH)', link: "https://medlineplus.gov/attentiondeficithyperactivitydisorder.html" },
        { english: 'At-term birth', spanish: 'Parto a término, Nacimiento a término' },
        { english: 'Audiologist', spanish: 'Audiólogo' },
        { english: 'Audiology', spanish: 'Audiología' },
        { english: 'Auditory canal', spanish: 'Conducto auditivo' },
        { english: 'Autism, Autism Spectrum Disorder (ASD)', spanish: 'Autismo, Trastorno del Espectro Autista (TEA)', link:"https://medlineplus.gov/lab-tests/autism-spectrum-disorder-asd-screening/" },
        { english: 'Awareness campaign', spanish: 'Campaña de concientización' },
        { english: 'Baby teeth', spanish: 'Dientes de leche', link:"https://medlineplus.gov/ency/imagepages/1138.htm" },
        { english: 'Balance', spanish: 'Balance' },
        { english: 'Baldness', spanish: 'Calvicie', link:"https://medlineplus.gov/hairloss.html" },
        { english: 'Bandage', spanish: 'Venda, Vendaje' },
        { english: 'Bassinet', spanish: 'Moisés' },
        { english: 'Bed rest', spanish: 'Reposo en cama, Reposo absoluto' },
        { english: 'Bedpan', spanish: 'Bacinilla, Cuña, Chata, Orinal de cama' },
        { english: 'Bedridden', spanish: 'Postrado en cama' },
        { english: 'Bedsore', spanish: 'Úlcera por presión, Llaga de cama' },
        { english: 'Behavior', spanish: 'Comportamiento, Conducta' },
        { english: 'Belching', spanish: 'Eructos, Eructación', link:"https://medlineplus.gov/ency/article/003080.htm" },
        { english: 'Bell Palsy', spanish: 'Parálisis de Bell. Parálisis facial periférica', link:"https://medlineplus.gov/bellspalsy.html" },
        { english: 'Belly binder', spanish: 'Faja abdominal' },
        { english: 'Bend over', spanish: 'Inclinarse hacia adelante, Agacharse' },
        { english: 'Benign', spanish: 'Benigno' },
        { english: 'Bereavement', spanish: 'Duelo' },
        { english: 'Big toe', spanish: 'Dedo gordo del pie' },
        { english: 'Bile', spanish: 'Bilis', link:"https://medlineplus.gov/ency/article/002237.htm" },
        { english: 'Bile duct', spanish: 'Conducto biliar' },
        { english: 'Biopsy', spanish: 'Biopsia' },
        { english: 'Bipolar disorder', spanish: 'Trastorno bipolar', link:"https://medlineplus.gov/bipolardisorder.html" },
        { english: 'Birth', spanish: 'Parto, Nacimiento' },
        { english: 'Birth canal', spanish: 'Canal de parto' },
        { english: 'Birth certificate', spanish: 'Acta de nacimiento' },
        { english: 'Birth control method', spanish: 'Método anticonceptivo', link:"https://medlineplus.gov/birthcontrol.html"},
        { english: 'Birth control pill, Contraceptive', spanish: 'Píldora anticonceptiva, Pastilla anticonceptiva, Anticonceptivo', link:"https://medlineplus.gov/ency/article/007460.htm" },
        { english: 'Bite (Animal)', spanish: 'Mordedura' },
        { english: 'Bite (Insect), Sting', spanish: 'Picadura' },
        { english: 'Black eye', spanish: 'Ojo morado', link:"https://medlineplus.gov/ency/imagepages/1688.htm" },
        { english: 'Blackhead', spanish: 'Punto negro', link:"https://medlineplus.gov/ency/article/003238.htm" },
        { english: 'Bladder', spanish: 'Vejiga' },
        { english: 'Bladder stone', spanish: 'Cálculo vesical. Piedra en la vejiga', link:"https://medlineplus.gov/ency/article/001275.htm" },
        { english: 'Bland diet', spanish: 'Dieta blanda', link:"https://medlineplus.gov/ency/patientinstructions/000068.htm" },
        { english: 'Bleeding', spanish: 'Hemorragia, sangrado' },
        { english: 'Blindness', spanish: 'Ceguera', link:"https://medlineplus.gov/visionimpairmentandblindness.html" },
        { english: 'Blink', spanish: 'Parpadear' },
        { english: 'Blister', spanish: 'Ampolla', link:"https://medlineplus.gov/blisters.html" },
        { english: 'Bloating', spanish: 'Hinchazón abdominal, Distensión abdominal', link:"https://medlineplus.gov/ency/article/003123.htm" },
        { english: 'Blockage', spanish: 'Obstrucción' },
        { english: 'Blood clot', spanish: 'Coágulo de sangre', link:"https://medlineplus.gov/bloodclots.html" },
        { english: 'Blood culture', spanish: 'Hemocultivo', link:"https://medlineplus.gov/ency/article/003744.htm" },
        { english: 'Blood flow', spanish: 'Flujo sanguíneo, Circulación' },
        { english: 'Blood pressure', spanish: 'Presión arterial, Presión sanguínea' },
        { english: 'Blood pressure cuff', spanish: 'Brazalete de presión arterial, Tensiómetro' },
        { english: 'Blood sample', spanish: 'Muestra de sangre' },
        { english: 'Blood sugar, Glucose', spanish: 'Azúcar en sangre, Glucosa' },
        { english: 'Blood sugar log', spanish: 'Registro de azúcar en sangre' },
        { english: 'Blood vessel', spanish: 'Vaso sanguíneo' },
        { english: 'Blood work', spanish: 'Análisis/Exámenes/Pruebas/Estudios de sangre' },
        { english: 'Bloodstream', spanish: 'Torrente sanguíneo' },
        { english: 'Blurred vision', spanish: 'Visión borrosa', link:"https://medlineplus.gov/ency/article/003029.htm" },
        { english: 'Bone density', spanish: 'Densidad ósea, Densidad de los huesos', link:"https://medlineplus.gov/bonedensity.html" },
        { english: 'Bone marrow', spanish: 'Médula ósea' },
        { english: 'Booster shot', spanish: 'Dosis de refuerzo' },
        { english: 'Bottle (Baby)', spanish: 'Biberón, mamadera, tetero' },
        { english: 'Bottle (Medication)', spanish: 'Frasco (de medicamentos)' },
        { english: 'Bottle feeding', spanish: 'Alimentación con biberón, Dar del biberón' },
        { english: 'Bowel movement', spanish: 'Defecación, Evacuación intestinal', link:"https://medlineplus.gov/bowelmovement.html" },
        { english: 'Brace (Orthopedic Device)', spanish: 'Aparato ortopédico' },
        { english: 'Braces (Dental)', spanish: 'Brackets, Frenillos dentales' },
        { english: 'Brain', spanish: 'Cerebro' },
        { english: 'Brain death', spanish: 'Muerte cerebral' },
        { english: 'Brand name', spanish: 'Nombre comercial, Nombre de marca' },
        { english: 'Break down', spanish: 'Quebrarse (emocionalmente), colapsar, derrumbarse' },
        { english: 'Breast', spanish: 'Mama, Seno' },
        { english: 'Breast cancer', spanish: 'Cáncer de mama', link:"https://medlineplus.gov/ency/article/000913.htm" },
        { english: 'Breast mass', spanish: 'Bulto en la mama', link:"https://medlineplus.gov/ency/article/003155.htm" },
        { english: 'Breast pump', spanish: 'Extractor de leche, Bomba de pecho' },
        { english: 'Breastfeeding, Lactation', spanish: 'Amamantamiento, Lactancia' },
        { english: 'Breathing tube', spanish: 'Tubo respiratorio' },
        { english: 'Breech delivery', spanish: 'Parto de nalgas', link:"https://medlineplus.gov/ency/patientinstructions/000623.htm" },
        { english: 'Bridge (Dental)', spanish: 'Puente dental' },
        { english: 'Bronchi', spanish: 'Bronquios' },
        { english: 'Bronchioles', spanish: 'Bronquiolos', link:"https://medlineplus.gov/ency/imagepages/19346.htm"},
        { english: 'Bronchitis', spanish: 'Bronquitis', link:"https://medlineplus.gov/acutebronchitis.html"},
        { english: 'Bronchospasm', spanish: 'Broncoespasmo' },
        { english: 'Bruise', spanish: 'Moretón, Hematoma', link:"https://medlineplus.gov/bruises.html" },
        { english: 'Buildup', spanish: 'Acumulación' },
        { english: 'Bulb syringe', spanish: 'Perilla de succión, Jeringa de pera' },
        { english: 'Bump', spanish: 'Bulto, Chichón, Protuberancia' },
        { english: 'Bunion', spanish: 'Juanete', link:"https://medlineplus.gov/ency/article/001231.htm" },
        { english: 'Burn', spanish: 'Quemadura', link:"https://medlineplus.gov/ency/article/000030.htm" },
        { english: 'Burning (sensation)', spanish: 'Ardor, Sensación de ardor' },
        { english: 'Burp', spanish: 'Eructar' },
        { english: 'Bursa (Musculoskeletal)', spanish: 'Bolsa sinovial' },
        { english: 'Burst', spanish: 'Reventar(se)' },
        { english: 'Buttock', spanish: 'Nalga, Glúteo' },
        { english: 'Buzzing', spanish: 'Zumbido' },
        { english: 'C-Section, Caesarean Section', spanish: 'Cesárea', link:"https://medlineplus.gov/cesareandelivery.html" },
        { english: 'Calf', spanish: 'Pantorrilla' },
        { english: 'Callus', spanish: 'Callo', link:"https://medlineplus.gov/cornsandcalluses.html" },
        { english: 'Cane', spanish: 'Bastón' },
        { english: 'Canker sore', spanish: 'Afta / Úlcera bucal', link:"https://medlineplus.gov/cankersores.html" },
        { english: 'Car seat, Child safety seat', spanish: 'Asiento de seguridad para automóvil, Silla de seguridad infantil' },
        { english: 'Carbohydrates', spanish: 'Carbohidratos', link:"https://medlineplus.gov/ency/article/002469.htm" },
        { english: 'Cardiac arrest', spanish: 'Paro cardíaco', link:"https://medlineplus.gov/ency/article/007640.htm" },
        { english: 'Cardiomyopathy', spanish: 'Cardiomiopatía', link:"https://medlineplus.gov/cardiomyopathy.html" },
        { english: 'Cardiopulmonary Resuscitation (CPR)', spanish: 'Reanimación Cardiopulmonar (RCP)', link:"https://medlineplus.gov/ency/article/000013.htm"},
        { english: 'Caregiver', spanish: 'Cuidador' },
        { english: 'Carpal tunnel syndrome', spanish: 'Síndrome del túnel carpiano', link:"https://medlineplus.gov/carpaltunnelsyndrome.html" },
        { english: 'Carrier', spanish: 'Portador' },
        { english: 'Cartilage', spanish: 'Cartílago' },
        { english: 'Case manager', spanish: 'Administrador/Coordinador/Gestor de casos' },
        { english: 'Cast', spanish: 'Yeso' },
        { english: 'Cataract', spanish: 'Catarata', link:"https://medlineplus.gov/cataract.html" },
        { english: 'Catheter', spanish: 'Catéter' },
        { english: 'Cavities, Dental decay', spanish: 'Caries dentales', link:"https://medlineplus.gov/toothdecay.html" },
        { english: 'Celiac disease', spanish: 'Enfermedad celíaca', link:"https://medlineplus.gov/celiacdisease.html" },
        { english: 'Cerebral cortex', spanish: 'Corteza cerebral' },
        { english: 'Cerebral palsy', spanish: 'Parálisis cerebral', link:"https://medlineplus.gov/cerebralpalsy.html" },
        { english: 'Cervical cerclage', spanish: 'Cerclaje cervical' },
        { english: 'Cervix', spanish: 'Cuello uterino. Cérvix' },
        { english: 'Chagas disease', spanish: 'Enfermedad de Chagas, Mal de Chagas', link:"https://medlineplus.gov/chagasdisease.html" },
        { english: 'Chamber', spanish: 'Cavidad, Cámara' },
        { english: 'Chamomile', spanish: 'Manzanilla' },
        { english: 'Chaplain', spanish: 'Capellán' },
        { english: 'Charley horse (Muscular Cramp)', spanish: 'Calambre muscular, Calambre', link:"https://medlineplus.gov/ency/article/002066.htm" },
        { english: 'Cheek', spanish: 'Mejilla' },
        { english: 'Cheekbone', spanish: 'Pómulo' },
        { english: 'Chemotherapy', spanish: 'Quimioterapia', link:"https://medlineplus.gov/ency/article/002324.htm" },
        { english: 'Chest pain', spanish: 'Dolor de pecho, Dolor en el pecho', link:"https://medlineplus.gov/chestpain.html" },
        { english: 'Chest tightness', spanish: 'Opresión en el pecho, Presión en el pecho', link:"https://medlineplus.gov/ency/article/003079.htm" },
        { english: 'Chickenpox', spanish: 'Varicela', link:"https://medlineplus.gov/chickenpox.html" },
        { english: 'Chills', spanish: 'Escalofríos', link:"https://medlineplus.gov/ency/article/003091.htm" },
        { english: 'Chin', spanish: 'Mentón, Barbilla' },
        { english: 'Chlamydia', spanish: 'Clamidia', link:"https://medlineplus.gov/ency/article/001345.htm" },
        { english: 'Choke', spanish: 'Atragantarse, Ahogarse' },
        { english: 'Cholesterol', spanish: 'Colesterol', link:"https://medlineplus.gov/cholesterol.html" },
        { english: 'Chronic Obstructive Pulmonary Disease (COPD)', spanish: 'Enfermedad Pulmonar Obstructiva Crónica (EPOC', link:"https://medlineplus.gov/copd.html" },
        { english: 'Circumcision', spanish: 'Circuncisión', link:"https://medlineplus.gov/circumcision.html" },
        { english: 'Clavicle, Collarbone', spanish: 'Clavícula' },
        { english: 'Clinic', spanish: 'Clínica' },
        { english: 'Clotting disorder', spanish: 'Trastorno de la coagulación', link:"https://medlineplus.gov/bleedingdisorders.html" },
        { english: 'Coccyx, Tailbone', spanish: 'Cóccix' },
        { english: 'Coinsurance', spanish: 'Coseguro' },
        { english: 'Colonoscopy', spanish: 'Colonoscopía', link:"https://medlineplus.gov/colonoscopy.html" },
        { english: 'Color blindness', spanish: 'Color Blindness', link:"https://medlineplus.gov/colorblindness.html" },
        { english: 'Colorectal cancer', spanish: 'Cáncer colorrectal', link:"https://medlineplus.gov/colorectalcancer.html" },
        { english: 'Colostomy', spanish: 'Colostomía', link:"https://medlineplus.gov/ency/article/002942.htm" },
        { english: 'Colostrum', spanish: 'Calostro' },
        { english: 'Complete Blood Count (CBC)', spanish: 'Hemograma completo', link:"https://medlineplus.gov/lab-tests/complete-blood-count-cbc/" },
        { english: 'Compression stocking', spanish: 'Media de compresión', link:"https://medlineplus.gov/ency/patientinstructions/000597.htm" },
        { english: 'Computed Tomography (CT Scan), Computerized Axial Tomography (CAT Scan)', spanish: 'Tomografía Computarizada, Tomografía Axial Computarizada' },
        { english: 'Conceive', spanish: 'Concebir, Quedar embarazada' },
        { english: 'Condom', spanish: 'Condón / Preservativo' },
        { english: 'Congestion', spanish: 'Congestión' },
        { english: 'Conjunctivitis, Pinkeye', spanish: 'Conjuntivitis', link:"https://medlineplus.gov/ency/article/001010.htm" },
        { english: 'Consciousness', spanish: 'Consciencia, Estado de conciencia' },
        { english: 'Consent form', spanish: 'Formulario de consentimiento' },
        { english: 'Constipation', spanish: 'Estreñimiento', link:"https://medlineplus.gov/constipation.html" },
        { english: 'Contact lens', spanish: 'Lente de contacto' },
        { english: 'Contrast dye, Contrast medium', spanish: 'Líquido de contraste, Medio de contraste' },
        { english: 'Cope', spanish: 'Sobrellevar, Afrontar' },
        { english: 'Coronary disease', spanish: 'Enfermedad coronaria' , link:"https://medlineplus.gov/coronaryarterydisease.html"},
        { english: 'Cotton swab', spanish: 'Hisopo, Cotonete' },
        { english: 'Cough', spanish: 'Tos', link:"https://medlineplus.gov/cough.html" },
        { english: 'Cough syrup', spanish: 'Jarabe para la tos' },
        { english: 'Counseling', spanish: 'Consejería, Asesoramiento' },
        { english: 'CPAP machine', spanish: 'Máquina CPAP' },
        { english: 'Crack', spanish: 'Grieta, Fisura' },
        { english: 'Crankiness, Irritability', spanish: 'Mal humor, Irritabilidad' },
        { english: 'Cravings', spanish: 'Antojos' },
        { english: 'Creatinine', spanish: 'Creatinina' },
        { english: 'Crib Death', spanish: 'Muerte súbita del lactante', link:"https://medlineplus.gov/suddeninfantdeathsyndrome.html" },
        { english: 'Crick in the neck', spanish: 'Tortícolis, Rigidez en el cuello' },
        { english: 'Crouch', spanish: 'Agacharse, Ponerse en cuclillas' },
        { english: 'Crushing pain', spanish: 'Dolor opresivo, Dolor aplastante' },
        { english: 'Crutch', spanish: 'Muleta' },
        { english: 'Culture', spanish: 'Cultivo' },
        { english: 'Cyst', spanish: 'Quiste' },
        { english: 'Cystitis', spanish: 'Cistitis', link:"https://medlineplus.gov/ency/article/000526.htm" },
        { english: 'Dandruff', spanish: 'Caspa', link:"https://medlineplus.gov/...ruffcradlecapandotherscalpconditions.html" },
        { english: 'Death certificate', spanish: 'Acta de defunción' },
        { english: 'Deceased', spanish: 'Fallecido, Difunto' },
        { english: 'Defibrillator', spanish: 'Desfibrilador', link:"https://medlineplus.gov/pacemakersandimplantabledefibrillators.html" },
        { english: 'Dehydration', spanish: 'Deshidratación', link:"https://medlineplus.gov/ency/article/000982.htm" },
        { english: 'Delivery', spanish: 'Parto, Alumbramiento' },
        { english: 'Labor and delivery room', spanish: 'Sala de parto' },
        { english: 'Dental floss', spanish: 'Hilo dental' },
        { english: 'Denture', spanish: 'Dentadura postiza, Prótesis dental' },
        { english: 'Deviated septum', spanish: 'Tabique desviado / Desviación del tabique' },
        { english: 'Diabetes (mellitus)', spanish: 'Diabetes (mellitus)', link:"https://medlineplus.gov/diabetes.html" },
        { english: 'Diabetes Ttpe 1', spanish: 'Diabetes tipo 1', link:"https://medlineplus.gov/diabetestype1.html" },
        { english: 'Diabetes type 2', spanish: 'Diabetes tipo 2', link:"https://medlineplus.gov/diabetestype2.html" },
        { english: 'Diabetic retinopathy', spanish: 'Retinopatía diabética', link:"https://medlineplus.gov/diabeticeyeproblems.html" },
        { english: 'Diagnosis', spanish: 'Diagnóstico' },
        { english: 'Dialysis', spanish: 'Diálisis', link:"https://medlineplus.gov/dialysis.html" },
        { english: 'Diaper', spanish: 'Pañal' },
        { english: 'Diaphragm', spanish: 'Diaphragm', link:"https://medlineplus.gov/ency/imagepages/19072.htm" },
        { english: 'Dietitian, Nutritionist', spanish: 'Dietista, Nutricionista' },
        { english: 'Digestive tract', spanish: 'Tracto digestivo' },
        { english: 'Dilation and Curettage (D&C)', spanish: 'Dilatación y curetaje, Dilatación y raspado, Legrado uterino' ,link:"https://medlineplus.gov/ency/article/002914.htm"},
        { english: 'Diphtheria-Tetanus-Pertussis Vaccine (DPT, DT, DTaP, DTP)', spanish: 'Vacuna contra la difteria, el tétanos y la tos ferina', link:"https://www.ncbi.nlm.nih.gov/books/NBK500572/" },
        { english: 'Disability', spanish: 'Discapacidad', link:"https://medlineplus.gov/disabilities.html" },
        { english: 'Disabled', spanish: 'Discapacitado, Persona con discapacidad' },
        { english: 'Discharge', spanish: 'Secreción' },
        { english: 'Discharge', spanish: 'Alta médica (noun), Dar de alta (verb)' },
        { english: 'Discharge instructions', spanish: 'Instrucciones de alta' },
        { english: 'Discomfort', spanish: 'Molestia, Malestar' },
        { english: 'Diverticulitis', spanish: 'Diverticulitis', link:"https://medlineplus.gov/ency/article/000257.htm" },
        { english: 'Diverticulosis', spanish: 'Diverticulosis', link:"https://medlineplus.gov/ency/article/007668.htm" },
        { english: 'Dizziness', spanish: 'Mareo', link:"https://medlineplus.gov/dizzinessandvertigo.html" },
        { english: 'Doctor\'s office', spanish: 'Consultorio médico' },
        { english: 'Do-Not-Resuscitate order (DNR)', spanish: 'Orden de no resucitar, Orden de no reanimar', link:"https://medlineplus.gov/ency/patientinstructions/000473.htm" },
        { english: 'Dose', spanish: 'Dosis' },
        { english: 'Douche', spanish: 'Ducha vaginal' },
        { english: 'Down syndrome', spanish: 'Síndrome de Down',link:"https://medlineplus.gov/downsyndrome.html" },
        { english: 'Drainage', spanish: 'Drenaje - Secreción' },
        { english: 'Dressing', spanish: 'Gasa' },
        { english: 'Drowsiness', spanish: 'Somnolencia', link:"https://medlineplus.gov/ency/article/003208.htm" },
        { english: 'Drunk', spanish: 'Ebrio, Borracho' },
        { english: 'Dry cough', spanish: 'Tos seca' },
        { english: 'Dry skin', spanish: 'Piel seca' },
        { english: 'Dryness', spanish: 'Resequedad' },
        { english: 'Due Date', spanish: 'Fecha de parto' },
        { english: 'Dull Pain', spanish: 'Dolor sordo' },
        { english: 'Durable power of attorney for health care', spanish: 'Poder notarial duradero para atención médica, Poder legal médico duradero para la salud' },
        { english: 'Ear drops', spanish: 'Gotas para los oídos' },
        { english: 'Ear wax', spanish: 'Cerumen, Cera del oído' },
        { english: 'Ear, Nose and Throat (ENT) Specialist, ENT doctor', spanish: 'Otorrinolaringólogo' },
        { english: 'Eardrum', spanish: 'Tímpano' },
        { english: 'Earplug', spanish: 'Tapón para los oídos' },
        { english: 'Eating Disorder', spanish: 'Trastorno alimentario, trastorno alimenticio', link:"https://medlineplus.gov/eatingdisorders.html" },
        { english: 'Ectopic Pregnancy', spanish: 'Embarazo ectópico', link:"https://medlineplus.gov/ectopicpregnancy.html" },
        { english: 'Eczema', spanish: 'Eccema', link:"https://medlineplus.gov/eczema.html" },
        { english: 'Egg', spanish: 'Ovario' },
        { english: 'Electrocardiogram (ECG, EKG)', spanish: 'Electrocardiograma' },
        { english: 'Electroencephalogram (EEG)', spanish: 'Electroencefalograma' },
        { english: 'Emergency Room (ER)', spanish: 'Sala de emergencias' },
        { english: 'Endocrinologist', spanish: 'Endocrinólogo' },
        { english: 'Endocrinology', spanish: 'Endocrinología' },
        { english: 'Endoscopy', spanish: 'Endoscopía', link:"https://medlineplus.gov/endoscopy.html" },
        { english: 'End-Stage Renal Disease (ESRD)', spanish: 'Enfermedad renal terminal (ERT)' },
        { english: 'Enema', spanish: 'Enema' },
        { english: 'Enlarged Prostate', spanish: 'Próstata agrandada', link:"https://medlineplus.gov/enlargedprostatebph.html" },
        { english: 'Enroll', spanish: 'Inscribirse, Afiliarse' },
        { english: 'Epidural', spanish: 'Epidural' },
        { english: 'Epilepsy', spanish: 'Epilepsia', link:"https://medlineplus.gov/epilepsy.html" },
        { english: 'Erectile dysfunction', spanish: 'Disfunción eréctil', link:"https://medlineplus.gov/erectiledysfunction.html" },
        { english: 'Esophagus', spanish: 'Esófago' },
        { english: 'Estrogen', spanish: 'Estrógeno' },
        { english: 'Expiration Date', spanish: 'Fecha de vencimiento/caducidad/expiración' },
        { english: 'Eye Doctor', spanish: 'Doctor de los ojos, Oftalmólogo' },
        { english: 'Eye Drops', spanish: 'Gotas para los ojos' },
        { english: 'Eyestrain', spanish: 'Fatiga visual, Cansancio visual' },
        { english: 'Fainting', spanish: 'Desmayo', link:"https://medlineplus.gov/fainting.html"},
        { english: 'Fallopian tubes', spanish: 'Trompas de Falopio' },
        { english: 'False labor', spanish: 'Parto falso' },
        { english: 'Fasting', spanish: 'En ayuno, En ayunas', link:"https://medlineplus.gov/lab-tests/fasting-for-a-blood-test/" },
        { english: 'Fat', spanish: 'Grasa' },
        { english: 'Fatty liver', spanish: 'Higado graso', link:"https://medlineplus.gov/steatoticliverdisease.html" },
        { english: 'Feces, Stool', spanish: 'Heces' },
        { english: 'Feeding tube', spanish: 'Tubo de alimentación, Sonda de alimentación' },
        { english: 'Femur', spanish: 'Fémur' },
        { english: 'Fertilization', spanish: 'Fertilización, Fecundación' },
        { english: 'Fetus', spanish: 'Feto' },
        { english: 'Fiber intake', spanish: 'Ingesta / Consumo de fibra', },
        { english: 'Fibroid', spanish: 'Fibroide, Fibroma', link:"https://medlineplus.gov/uterinefibroids.html" },
        { english: 'Fibromyalgia', spanish: 'Fibromialgia', link:"https://medlineplus.gov/fibromyalgia.html" },
        { english: 'Fibula', spanish: 'Fíbula, Peroné' },
        { english: 'Fill in, Fill out (a form)', spanish: 'Rellenar, Completar (un formulario)' },
        { english: 'Fingertip', spanish: 'Yema del dedo, Punta del dedo' },
        { english: 'Flake', spanish: 'Escama' },
        { english: 'Flex', spanish: 'Flexionar' },
        { english: 'Flu, Influenza', spanish: 'Gripe, Influenza' , link:"https://medlineplus.gov/flu.html"},
        { english: 'Foley bag', spanish: 'Bolsa de drenaje de orina' },
        { english: 'Foley catheter', spanish: 'Cateter urinario, Sonda Foley' },
        { english: 'Food allegy', spanish: 'Alergia alimenticia, alergia a alimento' },
        { english: 'Food group', spanish: 'Grupo alimenticio' },
        { english: 'Food label', spanish: 'Etiqueta alimenticia' },
        { english: 'Food poisoning', spanish: 'Intoxicación alimentica, Envenenamiento por alimentos', link:"https://medlineplus.gov/ency/article/001652.htm" },
        { english: 'Forearm', spanish: 'Antebrazo' },
        { english: 'Foreskin', spanish: 'Prepucio' },
        { english: 'Foul-smelling', spanish: 'Maloliente' },
        { english: 'Front (desk), Reception', spanish: 'Recepción' },
        { english: 'Full-term', spanish: 'A término completo' },
        { english: 'Gallbladder', spanish: 'Vesícula Biliar', link:"https://www.medlineplus.gov/gallbladderdiseases.html?_gl=1*hvewau*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjIzMTEkajUwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjIzMTEkajUwJGwwJGgw"},
        { english: 'Gallstones', spanish: 'Cálculos Biliares', link:"https://www.medlineplus.gov/gallstones.html?_gl=1*xhohb9*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjIzODAkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjIzODAkajYwJGwwJGgw"},
        { english: 'Gangrene', spanish: 'Gangrena', link:"https://www.medlineplus.gov/gangrene.html?_gl=1*1pt33qa*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI0NDgkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI0NDgkajYwJGwwJGgw"},
        { english: 'Gastroenteritis', spanish: 'Gastroenteritis',},
        { english: 'Genetic Disorders', spanish: 'Trastornos Genéticos', link:"https://www.medlineplus.gov/geneticdisorders.html?_gl=1*1e3l7lg*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI1NTQkajQxJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI1NTQkajQxJGwwJGgw"},
        { english: 'Genital Herpes', spanish: 'Herpes genital', link:"https://www.medlineplus.gov/genitalherpes.html?_gl=1*v3wqpy*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI2MjAkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI2MjAkajYwJGwwJGgw"},
        { english: 'Genital Warts', spanish: 'Verrugas genitales', link:"https://www.medlineplus.gov/genitalwarts.html?_gl=1*1212icd*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI2MzAkajUwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI2MzAkajUwJGwwJGgw"},
        { english: 'GERD - Gastroesophageal reflux disease', spanish: 'Enfermedad por reflujo gastroesofágico (ERGE)', link:"https://www.medlineplus.gov/gerd.html?_gl=1*7a20at*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI2OTQkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI2OTQkajYwJGwwJGgw"},
        { english: 'Glaucoma', spanish: 'Glaucoma', link:"https://www.medlineplus.gov/glaucoma.html?_gl=1*q1cklu*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI3NTYkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI3NTYkajYwJGwwJGgw"},
        { english: 'Gonorrhea', spanish: 'Gonorrea', link:"https://www.medlineplus.gov/gonorrhea.html?_gl=1*1h6oya9*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI4MDckajkkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI4MDckajkkbDAkaDA."},
        { english: 'Gout - Gouty arthritis', spanish: 'Gota - Artritis gotosa', link:"https://www.medlineplus.gov/gout.html?_gl=1*11qxnb1*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI4MTYkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI4MTYkajYwJGwwJGgw"},
        { english: 'Gum disease - Gingivitis', spanish: 'Gingivitis', link:"https://www.medlineplus.gov/gumdisease.html?_gl=1*1q6gq2v*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI5MjQkajM1JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI5MjQkajM1JGwwJGgw"},
        { english: 'H1N1 Flu - Swine Flu', spanish: 'Gripe porcina', link:"https://www.medlineplus.gov/h1n1fluswineflu.html?_gl=1*brqqpf*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI5ODkkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjI5ODkkajYwJGwwJGgw"},
        { english: 'Hantavirus Infections', spanish: 'Infecciones por Hantavirus', link:"https://www.medlineplus.gov/hantavirusinfections.html?_gl=1*10h5iv7*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMwNTEkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMwNTEkajYwJGwwJGgw"},
        { english: 'Hay Fever', spanish: 'Alergia al polen', link:"https://www.medlineplus.gov/hayfever.html?_gl=1*2y387x*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMwOTIkajE5JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMwOTIkajE5JGwwJGgw"},
        { english: 'Head Lice - Pediculosis', spanish: 'Piojos - Pediculosis', link:"https://www.medlineplus.gov/headlice.html?_gl=1*1nx1x8i*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMxMzUkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMxMzUkajYwJGwwJGgw"},
        { english: 'Hearing aids', spanish: 'Audífonos', link:"https://www.medlineplus.gov/hearingaids.html?_gl=1*jtuvad*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMxOTAkajUkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMxOTAkajUkbDAkaDA."},
        { english: 'Heart Attack - Myocardial infarction', spanish: 'Ataque al corazón - Infarto de miocardio', link:"https://www.medlineplus.gov/heartattack.html?_gl=1*o2azie*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMyMzckajMyJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMyMzckajMyJGwwJGgw"},
        { english: 'Heart Failure - Cardiac failure, CHF, Congestive heart failure, Left-sided heart failure, Right-sided heart failure', spanish: 'Insuficiencia cardíaca - Falla cardíaca', link:"https://www.medlineplus.gov/heartfailure.html?_gl=1*1ex8pc*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMzNjAkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjMzNjAkajYwJGwwJGgw"},
        { english: 'Heart Valve', spanish: 'Válvula cardíaca',},
        { english: 'Heartburn - Acid indigestion, Pyrosis', spanish: 'Acidez', link:"https://www.medlineplus.gov/heartburn.html?_gl=1*18jvlr1*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM1MDkkajUkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM1MDkkajUkbDAkaDA."},
        { english: 'Helicobacter pylori Infections', spanish: 'Infecciones por Helicobacter pylori', link:"https://www.medlineplus.gov/helicobacterpyloriinfections.html?_gl=1*15vuqkw*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM1NjUkajkkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM1NjUkajkkbDAkaDA."},
        { english: 'Hemochromatosis', spanish: 'Hemocromatosis', link:"https://www.medlineplus.gov/hemochromatosis.html?_gl=1*l45v82*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM2MDYkajI4JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM2MDYkajI4JGwwJGgw"},
        { english: 'Hemochromatosis - Iron overload disease', spanish: 'Hemocromatosis', link:"https://www.medlineplus.gov/hemochromatosis.html?_gl=1*l45v82*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM2MDYkajI4JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM2MDYkajI4JGwwJGgw"},
        { english: 'Hemorrhagic Fevers', spanish: 'Fiebre hemorrágica', link:"https://www.medlineplus.gov/hemorrhagicfevers.html?_gl=1*1gkyj95*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM2NzkkajQ0JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM2NzkkajQ0JGwwJGgw"},
        { english: 'Hemorrhagic Stroke', spanish: 'Accidente cerebrovascular hemorrágico', link:"https://www.medlineplus.gov/hemorrhagicstroke.html?_gl=1*lvz8fz*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM3MjEkajIkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM3MjEkajIkbDAkaDA."},
        { english: 'Hemorrhoids', spanish: 'Hemorroides',},
        { english: 'Hepatitis', spanish: 'Hepatitis',},
        { english: 'Hernia', spanish: 'Hernia',},
        { english: 'High Blood Presure', spanish: 'Hipertensión', link:"https://www.medlineplus.gov/highbloodpressure.html?_gl=1*1dokdrf*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM4NDYkajM5JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM4NDYkajM5JGwwJGgw"},
        { english: 'HIV - Human immunodeficiency virus', spanish: 'VIH - Virus de inmunodeficiencia humana', link:"https://www.medlineplus.gov/hiv.html?_gl=1*dic53g*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM4OTYkajU0JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM4OTYkajU0JGwwJGgw"},
        { english: 'Hives - Urticaria', spanish: 'Urticaria', link:"https://www.medlineplus.gov/hives.html?_gl=1*1eir6ko*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM5NTYkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM5NTYkajYwJGwwJGgw"},
        { english: 'Hormones', spanish: 'Hormonas',},
        { english: 'HPV - Human papillomavirus', spanish: 'HPV - Virus del papiloma humano', link:"https://www.medlineplus.gov/hpv.html?_gl=1*104qkhn*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM5ODgkajI4JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjM5ODgkajI4JGwwJGgw"},
        { english: 'Hyperglycemia - High blood glucose, High blood sugar', spanish: 'Hiperglucemia - Glucemia alta, alta azúcar en sangre', link:"https://www.medlineplus.gov/hyperglycemia.html?_gl=1*jbuq5s*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQwNzEkajkkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQwNzEkajkkbDAkaDA."},
        { english: 'Hyperthyroidism', spanish: 'Hipertiroidismo', link:"https://www.medlineplus.gov/hyperthyroidism.html?_gl=1*6cylnm*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQxMzUkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQxMzUkajYwJGwwJGgw"},
        { english: 'Hypoglycemia - Low blood sugar', spanish: 'Hipoglucemia - Glucemia baja, baja azúcar en sangre', link:"https://www.medlineplus.gov/hypoglycemia.html?_gl=1*njyzeg*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQxNzUkajIwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQxNzUkajIwJGwwJGgw"},
        { english: 'Hypothyroidism', spanish: 'Hipotiroidismo', link:"https://www.medlineplus.gov/hypothyroidism.html?_gl=1*mxmsgm*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQyNDEkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQyNDEkajYwJGwwJGgw"},
        { english: 'Hysterectomy', spanish: 'Histerectomía', link:"https://www.medlineplus.gov/hysterectomy.html?_gl=1*96vlq*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQyNDYkajU1JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQyNDYkajU1JGwwJGgw"},
        { english: 'Indigestion - Dyspepsia', spanish: 'Indigestión',},
        { english: 'Infertility', spanish: 'Infertilidad',},
        { english: 'Insomnia', spanish: 'Insomnio',},
        { english: 'Interstitial Cystitis - Bladder pain syndrome, IC, Painful bladder syndrome, PBS', spanish: 'Cistitis intersticial', link:"https://www.medlineplus.gov/interstitialcystitis.html?_gl=1*13uwr2j*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQzNzQkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQzNzQkajYwJGwwJGgw"},
        { english: 'Irritable Bowel Syndrome', spanish: 'Síndrome del colon irritable', link:"https://www.medlineplus.gov/irritablebowelsyndrome.html?_gl=1*9mjl5d*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ0NDckajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ0NDckajYwJGwwJGgw"},
        { english: 'Ischemic Stroke', spanish: 'Accidente cerebrovascular isquémico', link:"https://www.medlineplus.gov/ischemicstroke.html?_gl=1*fl8chb*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ0NTYkajUxJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ0NTYkajUxJGwwJGgw"},
        { english: 'Jaundice', spanish: 'Ictericia', link:"https://www.medlineplus.gov/jaundice.html?_gl=1*180ct8w*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ1NDkkajU0JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ1NDkkajU0JGwwJGgw"},
        { english: 'Kaposi Sarcoma', spanish: 'Sarcoma de Kaposi', link:"https://www.medlineplus.gov/kaposisarcoma.html?_gl=1*152tp6a*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ1OTkkajQkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ1OTkkajQkbDAkaDA."},
        { english: 'Kidney', spanish: 'Riñón',},
        { english: 'Laboratory Tests', spanish: 'Análisis de laboratorio',},
        { english: 'Lead Poisoning', spanish: 'Saturnismo', link:"https://www.medlineplus.gov/leadpoisoning.html?_gl=1*1tv8vud*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ2NzUkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ2NzUkajYwJGwwJGgw"},
        { english: 'LDL: The "Bad" Cholesterol', spanish: 'El colesterol "malo"', link:"https://www.medlineplus.gov/ldlthebadcholesterol.html?_gl=1*15fkx5s*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ3NTUkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ3NTUkajYwJGwwJGgw"},
        { english: 'Leukemia', spanish: 'Leucemia', },
        { english: 'Listeria Infections - Listeriosis', spanish: 'Infecciones por Listeria - Listeriosis', link:"https://www.medlineplus.gov/listeriainfections.html?_gl=1*1s6f4e5*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ4NDgkajI3JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ4NDgkajI3JGwwJGgw"},
        { english: 'Liver', spanish: 'Hígado',},
        { english: 'Lupus', spanish: 'Lupus',},
        { english: 'Lymphedema', spanish: 'Linfedema', link:"https://www.medlineplus.gov/lymphedema.html?_gl=1*xzez30*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ5MjkkajMzJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjQ5MzAkajMyJGwwJGgw"},
        { english: 'Lymphoma', spanish: 'Linfoma',},
        { english: 'Mammography', spanish: 'Mamografía',},
        { english: 'Mastectomy', spanish: 'Mastectomía', link:"https://www.medlineplus.gov/mastectomy.html?_gl=1*13hbsrp*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUwMjIkajM0JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUwMjIkajM0JGwwJGgw"},
        { english: 'Measles', spanish: 'Sarampión - Rubeola', link:"https://www.medlineplus.gov/measles.html?_gl=1*1ij42zr*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUwNzYkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUwNzYkajYwJGwwJGgw"},
        { english: 'Medical history', spanish: 'Historial médico / Antecedentes médicos',},
        { english: 'Melanoma', spanish: 'Melanoma',},
        { english: 'Meningitis', spanish: 'Meningitis', link:"https://www.medlineplus.gov/meningitis.html?_gl=1*18uqxhb*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUxMzQkajIkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUxMzQkajIkbDAkaDA."},
        { english: 'Menopause', spanish: 'Menopausia',},
        { english: 'Metabolic Disorders', spanish: 'Trastornos metabólicos',},
        { english: 'Migraine', spanish: 'Migraña',},
        { english: 'Mild headache', spanish: 'Dolor de cabeza leve',},
        { english: 'Miscarriage', spanish: 'Aborto espontáneo',},
        { english: 'Molds', spanish: 'Hongos',},
        { english: 'Moles', spanish: 'Lunares',},
        { english: 'Mood Disorders', spanish: 'Trastornos del estado de ánimo',},
        { english: 'Monkeypox - Mpox', spanish: 'Viruela del mono', link:"https://www.medlineplus.gov/mpox.html?_gl=1*b7qqep*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUzNjUkajQkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjUzNjUkajQkbDAkaDA."},
        { english: 'MRI scans', spanish: 'Resonancia magnética',},
        { english: 'Mumps', spanish: 'Paperas',},
        { english: 'Muscle cramp', spanish: 'Calambre',},
        { english: 'Myalgic Encephalomyelitis/Chronic Fatigue Syndrome', spanish: 'Encefalomielitis miálgica/Síndrome de fatiga crónica', link:"https://www.medlineplus.gov/myalgicencephalomyelitischronicfatiguesyndrome.html?_gl=1*di5224*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU0ODUkajIwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU0ODUkajIwJGwwJGgw"},
        { english: 'Myalgic Encephalomyelitis/Chronic Fatigue Syndrome', spanish: 'Encefalomielitis miálgica/Síndrome de fatiga crónica', link:"https://www.medlineplus.gov/myalgicencephalomyelitischronicfatiguesyndrome.html?_gl=1*di5224*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU0ODUkajIwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU0ODUkajIwJGwwJGgw"},
        { english: 'Myositis', spanish: 'Miositis',},
        { english: 'Nosebleed', spanish: 'Hemorragia nasal',},
        { english: 'Obsessive-Compulsive Disorder', spanish: 'Trastorno obsesivo-compulsivo',},
        { english: 'Occupational Therapy', spanish: 'Terapia ocupacional',},
        { english: 'Open Heart Surgery', spanish: 'Cirugía a corazón abierto',},
        { english: 'Pain Relievers / Pain Killers', spanish: 'Analgésicos',},
        { english: 'Panic Disorders', spanish: 'Trastornos de pánico', link:"https://www.medlineplus.gov/panicdisorder.html?_gl=1*1eozy6y*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU3NTYkajQ3JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU3NTYkajQ3JGwwJGgw"},
        { english: 'Paraplegia', spanish: 'Paraplejía',},
        { english: 'Parathyroid Disorders', spanish: 'Trastornos de las glándulas paratiroides',},
        { english: 'Pelvic Floor Disorders', spanish: 'Trastornos del suelo pélvico',},
        { english: 'Peritoneal Disorders', spanish: 'Trastornos peritoneales', link:"https://www.medlineplus.gov/peritonealdisorders.html?_gl=1*auenvn*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU4NTMkajI5JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjU4NTMkajI5JGwwJGgw"},
        { english: 'Phantom Limb', spanish: 'Miembro fantasma',},
        { english: 'Phantom Pain', spanish: 'Dolor fantasma',},
        { english: 'Pink eye', spanish: 'Conjuntivitis', link:"https://www.medlineplus.gov/pinkeye.html?_gl=1*1c5a87j*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjYwMDkkajIxJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjYwMDkkajIxJGwwJGgw"},
        { english: 'Pneumonia', spanish: 'Neumonía', link:"https://www.medlineplus.gov/pneumonia.html?_gl=1*1242rdk*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjYxNDckajEyJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjYxNDckajEyJGwwJGgw"},
        { english: 'Poisoning', spanish: 'Envenenamiento',},
        { english: 'Postpartum Care', spanish: 'Cuidado postparto',},
        { english: 'Postpartum Depression', spanish: 'Depresión postparto',},
        { english: 'Pregnancy', spanish: 'Embarazo',},
        { english: 'Prosthetic Limbs', spanish: 'Prótesis de extremidades',},
        { english: 'Pubic Lice', spanish: 'Ladilla', link:"https://www.medlineplus.gov/pubiclice.html?_gl=1*knccfa*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjYzMTIkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjYzMTIkajYwJGwwJGgw"},
        { english: 'Rabies', spanish: 'Rabia',},
        { english: 'Rash', spanish: 'Sarpullido', link:"https://www.medlineplus.gov/rashes.html?_gl=1*b188fe*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY0MzIkajkkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY0MzIkajkkbDAkaDA."},
        { english: 'Reflux', spanish: 'Reflujo',},
        { english: 'Restless Legs', spanish: 'Síndrome de piernas inquietas', link:"https://www.medlineplus.gov/restlesslegs.html?_gl=1*w46hkb*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY0ODYkajMzJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY0ODYkajMzJGwwJGgw"},
        { english: 'Retinal Disorders', spanish: 'Trastornos de la retina', link:"https://www.medlineplus.gov/retinaldisorders.html?_gl=1*1epe8rv*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY1NjgkajM4JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY1NjgkajM4JGwwJGgw"},
        { english: 'Rheumatoid Arthritis', spanish: 'Artritis reumatoide',},
        { english: 'Rickets', spanish: 'Raquitismo', link:"https://www.medlineplus.gov/rickets.html?_gl=1*p0xkty*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY2NjUkajIkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY2NjUkajIkbDAkaDA."},
        { english: 'Scabies', spanish: 'Sarna',},
        { english: 'Schizophrenia', spanish: 'Esquizofrenia',},
        { english: 'Sciatica', spanish: 'Ciática', link:"https://www.medlineplus.gov/sciatica.html?_gl=1*3k5883*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY3MjIkajckbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY3MjIkajckbDAkaDA."},
        { english: 'Scoliosis', spanish: 'Escoliosis',},
        { english: 'Seizures', spanish: 'Convulsiones',},
        { english: 'Sepsis', spanish: 'Septicemia', link:"https://www.medlineplus.gov/sepsis.html?_gl=1*ft0zjh*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY4MDIkajM3JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY4MDIkajM3JGwwJGgw"},
        { english: 'Shingles', spanish: 'Herpes Zoster', link:"https://www.medlineplus.gov/shingles.html?_gl=1*ombfjf*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY4ODkkajM1JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY4ODkkajM1JGwwJGgw"},
        { english: 'Sickle Cell Disease', spanish: 'Anemia drepanocítica', link:"https://www.medlineplus.gov/sicklecelldisease.html?_gl=1*2z1ibu*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY5MjUkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY5MjUkajYwJGwwJGgw"},
        { english: 'Sleep Disorders', spanish: 'Trastornos del sueño',},
        { english: 'Smallpox', spanish: 'Viruela', link:"https://www.medlineplus.gov/smallpox.html?_gl=1*ror8cx*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY5ODkkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjY5ODkkajYwJGwwJGgw"},
        { english: 'Sore Throat', spanish: 'Dolor de garganta',},
        { english: 'Spinal Cord Diseases', spanish: 'Enfermedades de la médula espinal', link:"https://www.medlineplus.gov/spinalcorddiseases.html?_gl=1*1gb04ww*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcwNzEkajQwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcwNzEkajQwJGwwJGgw"},
        { english: 'Spleen Diseases', spanish: 'Enfermedades del bazo', link:"https://www.medlineplus.gov/spleendiseases.html?_gl=1*xvjlxi*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcwODckajI0JGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcwODckajI0JGwwJGgw"},
        { english: 'Sprains and Strains', spanish: 'Esguinces y distensiones',},
        { english: 'Stem Cells', spanish: 'Células madre',},
        { english: 'Stillbirth', spanish: 'Muerte fetal', link:"https://www.medlineplus.gov/stillbirth.html?_gl=1*1ffxzjb*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcxMjQkajYwJGwwJGgw*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcxMjQkajYwJGwwJGgw"},
        { english: 'Stuttering', spanish: 'Tartamudeo', link:"https://www.medlineplus.gov/stuttering.html?_gl=1*3rvgtb*_ga*MTMwNjM5NDQxOC4xNzgzMzY1MjI5*_ga_7147EPK006*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcyODAkajkkbDAkaDA.*_ga_P1FPTH9PL4*czE3ODkzMjIzMDEkbzckZzEkdDE3ODkzMjcyODAkajkkbDAkaDA."},
        { english: 'Swelling', spanish: 'Hinchazón',},
        { english: 'TB - Tuberculosis', spanish: 'Tuberculosis',},
        { english: 'TBI - Traumatic Brain Injury', spanish: 'Lesión cerebral traumática',},
        { english: 'Three Day Measles', spanish: 'Sarampión de tres días - Rubeola',},
        { english: 'Thrush', spanish: 'Tordo',},
        { english: 'Thymus', spanish: 'Timo',},
        { english: 'Tickborne Diseases', spanish: 'Enfermedades transmitidas por garrapatas',},
        { english: 'Tremors', spanish: 'Temblores',},
        { english: 'Ulcers', spanish: 'Úlceras',},
        { english: 'Underactive', spanish: 'Hipoactivo',},
        { english: 'Urine Sample', spanish: 'Muestra de orina',},
        { english: 'Vaccine', spanish: 'Vacuna',},
        { english: 'Wheat Allergy', spanish: 'Alergia al trigo',},
        { english: 'Wrinkles', spanish: 'Arrugas',},
        { english: 'Yeast Infections', spanish: 'Enfermedades por hongos',},
        { english: 'Yellow Fever', spanish: 'Fiebre amarilla',},
        { english: 'Zits', spanish: 'Granos',},
    ]

    const filteredTerms = glosario.filter((item) => {
        const search = term.toLowerCase().trim();
        if (!search) return true; // Si no hay búsqueda, muestra todos

            return (
            item.english.toLowerCase().includes(search) ||
            item.spanish.toLowerCase().includes(search)
            );
        });

        const handleInputChange = (e) => {
        setTerm(e.target.value);
        };

        const [position, setPosition] = useState({ x: 0, y: 0 });
    const [isDragging, setIsDragging] = useState(false);

    const dragStart = useRef({ x: 0, y: 0 });

    const handleMouseDown = (e) => {
        if (!draggable) return;

        setIsDragging(true);

        dragStart.current = {
            x: e.clientX - position.x,
            y: e.clientY - position.y
        };
    };

    const handleMouseMove = (e) => {
        if (!isDragging) return;

        setPosition({
            x: e.clientX - dragStart.current.x,
            y: e.clientY - dragStart.current.y
        });
    };

    const handleMouseUp = () => {
        setIsDragging(false);
    };
    useEffect(() => {
        if (!isDragging) return;

        window.addEventListener("mousemove", handleMouseMove);
        window.addEventListener("mouseup", handleMouseUp);

        return () => {
            window.removeEventListener("mousemove", handleMouseMove);
            window.removeEventListener("mouseup", handleMouseUp);
        };
    }, [isDragging]);

    return(
        <div className="flex flex-col w-full p-6 items-center gap-4" onMouseDown={handleMouseDown}
            style={{
                transform: `translate(${position.x}px, ${position.y}px)`,
                cursor: draggable
                    ? isDragging
                        ? "grabbing"
                        : "grab"
                    : "default"
            }}>
            <input onChange={handleInputChange} value={term} placeholder="Look for a term..." className={`border border-gray-500 rounded-md p-2 ${classNameInput}`}></input>
            <div className={`space-y-4 overflow-y-auto ${className}`}>
                {filteredTerms.length > 0 ? (
                filteredTerms.map((item, index) => (
                    <div key={index} className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                        <div className="flex flex-col items-start">
                        <h3 className="text-md font-semibold text-gray-800">
                            {item.english}
                        </h3>
                        <p className="text-gray-600 mt-1">
                            <span className="font-medium text-gray-500"></span>{" "}
                            {item.spanish}
                        </p>
                        </div>
                        {item.link?(<a
                        href={item.link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-blue-600 hover:text-blue-800 font-medium text-sm whitespace-nowrap"
                        >
                        More information →
                        </a>):(<span className="hidden"></span>)}
                    </div>
                    </div>
                ))
                ) : (
                <p className="text-center text-gray-500 py-10">
                    We couldn't find any terms like “{term}”
                </p>
                )}
            </div>
        </div>
    )
}